FROM debian:stretch
#COPY config/php.ini /usr/local/etc/php/

ENV TZ=America/Argentina/Buenos_Aires
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y \
  supervisor \
  curl \
  apache2 \
  libapache2-mod-php7.0 \
  php7.0-pgsql \
  php7.0-zip \
  php7.0-gd \
  php7.0-curl \
  php7.0-xml \
  php7.0-intl \
  php7.0-mbstring \
  php7.0-xmlrpc \
  php7.0-soap \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY docker/entrypoint.sh /
COPY docker/supervisor/apache.conf /etc/supervisor/conf.d/
COPY docker/apache/30-upload_size.ini /etc/php/7.0/apache2/conf.d/

#RUN cd /var/www && git clone --branch v3.4.3 https://github.com/moodle/moodle.git
COPY config.php /var/www/moodle-3.4.3/
ADD v3.4.3.tar.gz /var/www/
RUN chown www-data:www-data /var/www/moodle-3.4.3

ENV APACHE_DOCUMENT_ROOT /var/www/moodle-3.4.3
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

ENTRYPOINT ["/entrypoint.sh"]
